In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

For importing particular functions you can use the following

In [3]:
from numpy import pi 

Addition in python is equivalent to Concatenation

In [4]:
a=[1,2,4,5]
b=[9,5,6,7]
c=a+b
c
type(a)
type(a[0])
d=[1,"hello"]
type(d[1])

[1, 2, 4, 5, 9, 5, 6, 7]

list

int

str

Basics of Numpy

In [5]:
a=np.array([[1,2,2,4],[5,15,7,8]])
a.shape
a.itemsize
type(a)
type(a[0])
type(a[0][0])

(2, 4)

8

numpy.ndarray

numpy.ndarray

numpy.int64

In [6]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
c=np.arange(5,50,10)
c

array([ 5, 15, 25, 35, 45])

In [8]:
d=np.linspace(0,2*pi,100)
d
np.sin(d)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

Printing Arrays

In [9]:
a=np.arange(12)
a
a.reshape((4,3))
a.reshape(4,3,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]]])

Arthimetic Operators

In [10]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a+b
a+b
a-b
b**2
10*np.sin(a)

array([20, 31, 42, 53])

array([20, 29, 38, 47])

array([0, 1, 4, 9])

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [11]:
A=np.array([[2,0],[0,1]])
B=np.array([[1,1],[3,4]])
A*B #Element wise multiplication
A.dot(B) #Array multiplication
np.dot(A,B) #Array multiplication in numpy

array([[2, 0],
       [0, 4]])

array([[2, 2],
       [3, 4]])

array([[2, 2],
       [3, 4]])

In [12]:
a=np.ones((2,3),dtype=int)
a
b=np.random.random((2,3))
b
a*=3
b+=a
b
b.sum()
b.min()
b.max()

array([[1, 1, 1],
       [1, 1, 1]])

array([[0.64581534, 0.62678793, 0.02753299],
       [0.22880326, 0.52801657, 0.87725905]])

array([[3.64581534, 3.62678793, 3.02753299],
       [3.22880326, 3.52801657, 3.87725905]])

20.93421513311995

3.0275329916307463

3.8772590471557447

Axis wise operations

In [13]:
b=np.arange(12).reshape(3,4)
b
b.sum(axis=0)
b.sum(axis=1)
b.min(axis=1)
b.cumsum(axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([12, 15, 18, 21])

array([ 6, 22, 38])

array([0, 4, 8])

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

Universal Functions

In [14]:
b=np.arange(3)
np.exp(b)
np.sqrt(b)
c=np.array([2.,-1.,4.])
np.add(b,c)

array([1.        , 2.71828183, 7.3890561 ])

array([0.        , 1.        , 1.41421356])

array([2., 0., 6.])

Indexing, Slicing and Iterating - 1D numpy array can be indexed, sliced and iterated over much like the lists and other python sequences.

In [15]:
a=np.arange(10)
a**3
a
a[2:5]
a[:6:2]=-10 
#Update the value from start i.e. 0 to excluding 6 as -10, the value is updated to -10 at 0,2,4
a
a[1:6:2]=-20
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 3, 4])

array([-10,   1, -10,   3, -10,   5,   6,   7,   8,   9])

array([-10, -20, -10, -20, -10, -20,   6,   7,   8,   9])

In [16]:
a=[1,2,3,4]
a
c=a*2
c

[1, 2, 3, 4]

[1, 2, 3, 4, 1, 2, 3, 4]