In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import math as m
import numpy as np

Why NumPy?

In [3]:
#Time
x = np.random.rand(10000)
y = np.random.rand(10000)
z=0
for i in range(10000):
    z += x[i]*y[i]
z

2505.1412300006596

In [4]:
#Time
x = np.random.rand(10000)
y = np.random.rand(10000)
z = np.dot(x,y)
z

2487.1217636097645

NumPy functions for creating arrays

In [5]:
x=np.zeros((3,4))
x
x=np.ones((2,3))
x
x=np.random.rand(3,4)
x
x=np.random.randn(2,3)
x
x=np.arange(1,100,2)
x
x=np.arange(0,100)
x
x=np.linspace(0,5,10)
x
x.reshape((2,5))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[0.79654364, 0.54701054, 0.53754566, 0.37988832],
       [0.03779339, 0.55368056, 0.5126112 , 0.79779137],
       [0.7552131 , 0.52594625, 0.38105033, 0.30143967]])

array([[-0.33937548,  0.07703033,  1.14614933],
       [ 0.62473038, -0.70773571,  0.3456714 ]])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222],
       [2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]])

In [6]:
python_list = [ 1,2,3 ]
x=np.array(python_list)
type(x)
x = np.array([ 2**i for i in range(10) if i!= 5 ])
x

numpy.ndarray

array([  1,   2,   4,   8,  16,  64, 128, 256, 512])

Array Broadcasting

In [7]:
np.ones((5,5))
np.ones((5,5))+np.arange(5*5).reshape(5,5)
np.ones((5,5)) + np.arange(5).reshape(5,1)
np.arange(10).reshape(-1,1) #Notice the use of -1
np.arange(10) + np.arange(10).reshape(-1,1)
np.ones((1,5)) + np.ones((5,1))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

Matrix Creation

In [8]:
np.eye(10)
x=np.diag(np.arange(10))
x
np.diag(x)
x=np.arange(15).reshape(5,3).T
x
x=np.arange(3).reshape(-1,1)
x
y=np.arange(3).reshape(1,-1)
y
np.dot(x,y)
x@y

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

array([[0],
       [1],
       [2]])

array([[0, 1, 2]])

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

Array Indexing and Slicing

x[i:j:k]
Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension. 
Negative k makes stepping go towards smaller indices.

In [9]:
x=np.arange(10)
x
x[3:7]
x[:-2]
x[0:6:2]
x[0:5:-1]
x[::-1]
x[-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([3, 4, 5, 6])

array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 2, 4])

array([], dtype=int64)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

9

Fancy Array Indexing

In [10]:
x=np.arange(10)
x
idx=np.array([7,-5,2])
x[idx]=-1
x
x<0
x[x<0] = np.arange(3)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1, -1,  3,  4, -1,  6, -1,  8,  9])

array([False, False,  True, False, False,  True, False,  True, False,
       False])

array([0, 1, 0, 3, 4, 1, 6, 2, 8, 9])

Reduction Operations

In [11]:
X = np.arange(100).reshape(10,10)
X
np.sum(X)
np.prod(X)
np.prod(X,axis=1)
np.min(X),np.max(X)
np.min(X,axis=0)
Y = X<1
Y
np.any(Y)
np.all(Y)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

4950

0

array([                  0,        335221286400,      72684900288000,
          2306992893004800,   29820834418636800,  227991539359584000,
       1233909752121446400, 5227941748053024000,    5769992716765184,
       1193853638847869952])

(0, 99)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

True

False

All the above functions can be called on array object directly.

In [12]:
X.max(axis=0)
(np.sqrt(X*X*X)<5000).all()
np.cumsum(np.ones((10,10)),axis=1)
#Cumulative operations don't change the shape of the array
np.cumsum(X,axis=0)

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

True

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 60,  64,  68,  72,  76,  80,  84,  88,  92,  96],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 156, 162, 168, 174, 180, 186, 192, 198, 204],
       [210, 217, 224, 231, 238, 245, 252, 259, 266, 273],
       [280, 288, 296, 304, 312, 320, 328, 336, 344, 352],
       [360, 369, 378, 387, 396, 405, 414, 423, 432, 441],
       [450, 460, 470, 480, 490, 500, 510, 520, 530, 540]])

Random numbers
- rng.rand(d0,d1,...,dn) - Random values in a given shape
- rng.randn(d0, d1, ...,dn) - Random standard normal
- rng.randint(lo, hi, size) - Random integers from lo to hi excluding hi.
- rng.choice(a, size, repl, p) - Sample from a
- rng.shuffle(a) - Permutation (in-place)
- rng.permutation(a) - Permutation (new array)

 Also, have parameterized distributions: beta, binomial, chisquare, exponential, dirichlet, gamma, laplace, lognormal, pareto, poisson, power...

Linear Algebra in Numpy

In [13]:
import numpy.linalg as la

- la.eye(3), Identity matrix
- la.trace(A), Trace
- la.column_stack((A,B)), Stack column wise
- la.row_stack((A,B,A)), Stack row wise
- la.qr, Computes the QR decomposition
- la.cholesky, Computes the Cholesky decomposition
- la.inv(A), Inverse
- la.solve(A,b), Solves  𝐴𝑥=𝑏  for  𝐴  full rank
- la.lstsq(A,b), Solves  argmin𝑥‖𝐴𝑥−𝑏‖2 
- la.eig(A), Eigenvalue decomposition
- la.eigh(A), Eigenvalue decomposition for symmetric or hermitian
- la.eigvals(A), Computes eigenvalues.
- la.svd(A, full), Singular value decomposition
- la.pinv(A), Computes pseudo-inverse of A