In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
#First 20 countries with employment data
countries = np.array(['Afghanistan','Albanis','Algeria','Angola','Argentina',
                     'Armenia','Australia','Austria','Azerbaijan','Bahamas',
                     'Bahrain','Bangladesh','Barbados','Belarus','Belgium',
                     'Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina'])

In [5]:
#Employment data in 2007 for those 20 countries
employment = np.array([55.70000076, 51.40000153, 50.5 , 75.69999695, 58.40000153, 
                       40.09999847, 61.5 , 57.09999847, 60.90000153, 66.59999847, 
                       60.40000153, 68.09999847, 66.90000153, 53.40000153, 48.59999847, 
                       56.79999924, 71.59999847, 58.40000153, 70.40000153, 41.20000076])

In [6]:
#Element Types
countries.dtype
employment.dtype
np.array([0,1,2,3]).dtype
np.array([1.0,1.5,2.0,2.5]).dtype
np.array([True, False, True]).dtype
np.array(['AL','AK','AZ','AR','CA']).dtype

dtype('<U22')

dtype('float64')

dtype('int64')

dtype('float64')

dtype('bool')

dtype('<U2')

In [7]:
#Looping
for country in countries:
    print(f'Examining country {country}')
for country in countries:
    print('Examining country {}'.format(country))

Examining country Afghanistan
Examining country Albanis
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Examining country Afghanistan
Examining country Albanis
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Ex

In [8]:
for i in range(len(countries)):
    country=countries[i]
    country_employment=employment[i]
    print('Country {} has employment {}'.format(country,country_employment))

Country Afghanistan has employment 55.70000076
Country Albanis has employment 51.40000153
Country Algeria has employment 50.5
Country Angola has employment 75.69999695
Country Argentina has employment 58.40000153
Country Armenia has employment 40.09999847
Country Australia has employment 61.5
Country Austria has employment 57.09999847
Country Azerbaijan has employment 60.90000153
Country Bahamas has employment 66.59999847
Country Bahrain has employment 60.40000153
Country Bangladesh has employment 68.09999847
Country Barbados has employment 66.90000153
Country Belarus has employment 53.40000153
Country Belgium has employment 48.59999847
Country Belize has employment 56.79999924
Country Benin has employment 71.59999847
Country Bhutan has employment 58.40000153
Country Bolivia has employment 70.40000153
Country Bosnia and Herzegovina has employment 41.20000076


In [9]:
#Numpy Functions
employment.mean()
employment.std()
employment.max()
employment.sum()

58.68500003850001

9.338269113687888

75.69999695

1173.70000077

In [10]:
def max_employment(countries,employment):
    max_value=0
    max_country=None
    for i in range(len(countries)):
        country=countries[i]
        c_employment=employment[i]
        if c_employment>max_value:
            max_value=c_employment
            max_country=country
    return (max_country,max_value)
maximum_country,maximum_value=max_employment(countries,employment)
maximum_country
maximum_value

'Angola'

75.69999695

In [11]:
#Using Numpy
def max_employment_np(countries, employement):
    i=employment.argmax()
    return (countries[i],employment[i])
maximum_country,maximum_value=max_employment(countries,employment)
maximum_country
maximum_value

'Angola'

75.69999695

Arithmetic Operations between two numpy arrays

In [12]:
a=np.array([1,2,3,4])
b=np.array([1,2,1,2])
a+b
a-b
a*b
a/b
a//b
a**b

array([2, 4, 4, 6])

array([0, 0, 2, 2])

array([1, 4, 3, 8])

array([1., 1., 3., 2.])

array([1, 1, 3, 2])

array([ 1,  4,  3, 16])

Arithmetic Operations between a numpy array and a single number

In [13]:
a=np.array([1,2,3,4])
b=2
a+b
a-b
a/b
a*b
a//b

array([3, 4, 5, 6])

array([-1,  0,  1,  2])

array([0.5, 1. , 1.5, 2. ])

array([2, 4, 6, 8])

array([0, 1, 1, 2])

Logical Operations with Numpy Arrays

In [14]:
a=np.array([True,True,False,False])
b=np.array([True,False,True,False])
a&b
a|b
~a
a&True
a&False
a|True
a|False

array([ True, False, False, False])

array([ True,  True,  True, False])

array([False, False,  True,  True])

array([ True,  True, False, False])

array([False, False, False, False])

array([ True,  True,  True,  True])

array([ True,  True, False, False])

Comaprison Operations between two Numpy Arrays

In [15]:
a=np.arange(5)
a
b=np.array([5,4,3,2,1])
b
a>b
a>=b
a<b
a<=b
a==b
a!=b

array([0, 1, 2, 3, 4])

array([5, 4, 3, 2, 1])

array([False, False, False,  True,  True])

array([False, False, False,  True,  True])

array([ True,  True,  True, False, False])

array([ True,  True,  True, False, False])

array([False, False, False, False, False])

array([ True,  True,  True,  True,  True])

Comparison operations between numpy array and single number

In [16]:
a=np.arange(8)
a
b=2
a>b
a>=b
a<b
a<=b
a==b
a!=b

array([0, 1, 2, 3, 4, 5, 6, 7])

array([False, False, False,  True,  True,  True,  True,  True])

array([False, False,  True,  True,  True,  True,  True,  True])

array([ True,  True, False, False, False, False, False, False])

array([ True,  True,  True, False, False, False, False, False])

array([False, False,  True, False, False, False, False, False])

array([ True,  True, False,  True,  True,  True,  True,  True])

In [17]:
#First 20 countries with employment data
countries = np.array(['Afghanistan','Albanis','Algeria','Angola','Argentina',
                     'Armenia','Australia','Austria','Azerbaijan','Bahamas',
                     'Bahrain','Bangladesh','Barbados','Belarus','Belgium',
                     'Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina'])

In [18]:
#Female school completion rate in 2007 for those 20 countries 
female_completion = np.array([ 97.35583, 104.62379, 103.02998, 95.14321, 103.69019, 
                              98.49185, 100.88828, 95.43974, 92.11484, 91.54804, 
                              95.98029, 98.22902, 96.12179, 119.28105, 97.84627, 
                              29.07386, 38.41644, 90.70509, 51.7478 , 95.45072 ])
# Male school completion rate in 2007 for those 20 countries 
male_completion = np.array([ 95.47622, 100.66476, 99.7926 , 91.48936, 103.22096, 
                            97.80458, 103.81398, 88.11736, 93.55611, 87.76347, 
                            102.45714, 98.73953, 92.22388, 115.3892 , 98.70502, 
                            37.00692, 45.39401, 91.22084, 62.42028, 90.66958 ])

In [19]:
def overall_completion_rate(female_completion,male_completion):
    return (female_completion+male_completion)/2
countries
overall_completion=overall_completion_rate(female_completion,male_completion)
overall_completion

array(['Afghanistan', 'Albanis', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina'],
      dtype='<U22')

array([ 96.416025, 102.644275, 101.41129 ,  93.316285, 103.455575,
        98.148215, 102.35113 ,  91.77855 ,  92.835475,  89.655755,
        99.218715,  98.484275,  94.172835, 117.335125,  98.275645,
        33.04039 ,  41.905225,  90.962965,  57.08404 ,  93.06015 ])

In [20]:
country_name='United States'

In [21]:
def standardize_data(values):
    std_values=(values-values.mean())/values.std()
    return std_values
std_employment=standardize_data(employment)
countries
std_employment

array(['Afghanistan', 'Albanis', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina'],
      dtype='<U22')

array([-0.31965231, -0.780123  , -0.87650077,  1.82207181, -0.03051941,
       -1.99019768,  0.30144772, -0.16973184,  0.23719615,  0.84758731,
        0.18365304,  1.00821665,  0.87971351, -0.56595055, -1.07996476,
       -0.20185762,  1.38301845, -0.03051941,  1.2545153 , -1.87240259])

In [22]:
a=np.array([1,2,3,4])
b=np.array([True,False,True,True])
a[b]

array([1, 3, 4])

In [23]:
a=np.array([1,2,3,2,1])
b=(a>=2)
a[b]
a[a>=2]

array([2, 3, 2])

array([2, 3, 2])

In [24]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,2,1])
b==2
a[b==2]

array([False,  True, False,  True, False])

array([2, 4])

In [25]:
def mean_time_for_paid_students(time_spent,days_to_cancel):
    return time_spent[days_to_cancel >= 7].mean()
# Time spent in the classroom in the first week for 20 students 
time_spent = np.array([ 12.89697233, 0. , 64.55043217, 0. , 24.2315615 , 39.991625 , 0. , 0. , 147.20683783, 0. , 0. , 0. , 45.18261617, 157.60454283, 133.2434615 , 52.85000767, 0. , 54.9204785 , 26.78142417, 0. ])
# Days to cancel for 20 students 
days_to_cancel = np.array([ 4, 5, 37, 3, 12, 4, 35, 38, 5, 37, 3, 3, 68, 38, 98, 2, 249, 2, 127, 35 ])
mean_time= mean_time_for_paid_students(time_spent, days_to_cancel)
mean_time

41.05400348545454

Shadow Copy
+= (inplace) vs + (not in place)
in place = updates value in same array

In [26]:
a=np.array([1,2,3,4])
b=a
b
a+=np.array([1,1,1,1])
b
a
id(a)
id(b)

array([1, 2, 3, 4])

array([2, 3, 4, 5])

array([2, 3, 4, 5])

4618582496

4618582496

In [27]:
a=np.array([1,2,3,4])
b=a
b
a=a+np.array([1,1,1,1])
b
a
id(a)
id(b)

array([1, 2, 3, 4])

array([1, 2, 3, 4])

array([2, 3, 4, 5])

4618427248

4618425168

In [28]:
a=np.array([1,2,3,4,5])
slice2=a[:3]
a
slice2[0]=100 #inplace
a

array([1, 2, 3, 4, 5])

array([100,   2,   3,   4,   5])